# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Experience
    url: /#experience
    weight: 20
  - name: Research
    url: /#publications
    weight: 30
  - name: Publications
    parent: Research
    url: /#publications
    weight: 31
  - name: Conferences
    parent: Research
    url: /#conferences
    weight: 32
  - name: Book Chapters
    parent: Research
    url: /#book-chapters
    weight: 33
  - name: Edited Books
    parent: Research
    url: /#edited-books
    weight: 34
  - name: Funded Projects
    parent: Research
    url: /#funded-projects
    weight: 35
  - name: Consultancy
    parent: Research
    url: /#consultancy
    weight: 36
  - name: Incubation
    parent: Research
    url: /#incubation
    weight: 37
  - name: Memberships
    url: /#memberships
    weight: 50
  - name: Foreign Visits
    url: /#foreign-visits
    weight: 60
  - name: Awards
    url: /#awards
    weight: 70
